language: go
go:
  - 1.11.x
sudo: false
install:
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - export GO111MODULE=on
  - (cd cmd/fnotime && go build)
  - (cd cmd/fnotime_dumpdb && go build)
  - (cd cmd/fnotime_timestamp && go build)
  - (cd cmd/fnotime_unflush && go build)
  - (cd fnotimed && go build)
  - ./goclean.sh
